In [43]:
class Employee:
    count_Emp = 0  # data member to count the number of the Employees

    def __init__(self, name, family, salary, department): # constructor to initialize name, family, salary, department
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count_Emp += 1  # Employee count

    def avg_salary(self):  # to find the average salary of the Employee
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.count_Emp
        print('Average salary of the Employee:', avg)

    def display(self):  # Displaying the Employee details
        print('Name of the Employee:', self.name)
        print('Family Members of the Employee:', self.family)
        print('Salary of the Employee Annually:', self.salary)
        print('Department Employee working:', self.department)
        print(f'{Fore.BLUE + Style.BRIGHT}***{Style.RESET_ALL}')


class Fulltime_Employee(Employee):  # inheriting the Employee class
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    def display(self):  # Displaying the Employee details
        print(f'{Fore.GREEN + Style.BRIGHT}Name of the Employee{Style.RESET_ALL}:', self.name)
        print('Family Members of the Employee:', self.family)
        print('Salary of the Employee Annually:', self.salary)
        print('Department of Employee:', self.department)
        print('Type of the Employment', self.emp_type)
        print(f'{Fore.BLUE + Style.BRIGHT}***{Style.RESET_ALL}')


emp1 = Employee('Ziva', '4', '620000', 'Manager')  # creating the instance of  the Employee class
emp2 = Fulltime_Employee('Rumana', '5', '820000', 'Software Developer',
                         'Fulltime')  # Creating the instances of Fulltime Employeeclass
emp3 = Fulltime_Employee('Zaahi', '4', '1400000', 'Web Developer', 'Fulltime')

print(f'{Fore.GREEN + Style.BRIGHT}Count of the Employees{Style.RESET_ALL}:', emp1.count_Emp)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()

Count of the Employees: 3
Average salary of the Employee: 206666.66666666666
Name of the Employee: Ziva
Family Members of the Employee: 4
Salary of the Employee Annually: 620000
Department Employee working: Manager
***
Name of the Employee: Rumana
Family Members of the Employee: 5
Salary of the Employee Annually: 820000
Department of Employee: Software Developer
Type of the Employment Fulltime
***
Name of the Employee: Zaahi
Family Members of the Employee: 4
Salary of the Employee Annually: 1400000
Department of Employee: Web Developer
Type of the Employment Fulltime
***


In [44]:
import pandas as pd
import numpy as np

random_vector = np.random.uniform(1, 20, 20)  # creating array of size 20 having only float in the range 1-20.
print("Random Vector of size 20: \n", random_vector)

random_vector = random_vector.reshape(4,5)  # reshape the array to 4 by 5
print("Numpy array after reshaping to 4 by 5:")
print(random_vector)

print("Replacing the max in each row by 0:")
# replace the max in each row by 0
# np.where returns element depending on condition
random_vector = np.where(random_vector == np.amax(random_vector, axis=1).reshape(-1,1), 0, random_vector)

print(random_vector)

Random Vector of size 20: 
 [19.07323411 17.57771715 10.01207261  3.34863888  2.67795855 14.35877208
 13.41245627 17.41368483  3.1818497  17.46376007 18.85551671 13.87919455
  6.35792494  1.28339909 12.65274355  5.70225826  2.65395348 18.97379861
 17.87283692 13.48640688]
Numpy array after reshaping to 4 by 5:
[[19.07323411 17.57771715 10.01207261  3.34863888  2.67795855]
 [14.35877208 13.41245627 17.41368483  3.1818497  17.46376007]
 [18.85551671 13.87919455  6.35792494  1.28339909 12.65274355]
 [ 5.70225826  2.65395348 18.97379861 17.87283692 13.48640688]]
Replacing the max in each row by 0:
[[ 0.         17.57771715 10.01207261  3.34863888  2.67795855]
 [14.35877208 13.41245627 17.41368483  3.1818497   0.        ]
 [ 0.         13.87919455  6.35792494  1.28339909 12.65274355]
 [ 5.70225826  2.65395348  0.         17.87283692 13.48640688]]
